#include <main_menu_stage.h>

#include <tmenu.h>
#include <ncurses.h>
#include <colors.h>
#include <stdlib.h>
#include <deck.h>
#include <card.h>

#define RAND_CARD_COUNT     20

/* Title */
/* Generated by curses-art: https://github.com/codigoymate/curses-art */
chtype title_data[] = {
0x501371, 0x501371, 0x501371, 0x501377, 0x501377, 0x501371, 0x501371, 0x501371, 0x0000, 0x50136C, 0x501377, 0x501371, 0x501371, 0x501371, 0x501371, 0x50136B, 
0x0000, 0x0000, 0x501378, 0x501378, 0x0000, 0x0000, 0x0000, 0x0000, 0x501378, 0x501378, 0x0000, 0x0000, 0x50136C, 0x501371, 0x501371, 0x501371, 
0x501371, 0x501371, 0x0000, 0x0000, 0x50136C, 0x501371, 0x501371, 0x501371, 0x501371, 0x50136B, 0x0000, 0x0000, 0x0000, 0x0000, 0x501378, 0x501378, 
0x0000, 0x0000, 0x0000, 0x0000, 0x501378, 0x501378, 0x0000, 0x0000, 0x0000, 0x0000, 0x501378, 0x501378, 0x0000, 0x501378, 0x501378, 0x0000, 
0x0000, 0x0000, 0x0000, 0x501378, 0x501378, 0x0000, 0x50136C, 0x501375, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x50136C, 0x501375, 
0x0000, 0x0000, 0x0000, 0x0000, 0x501374, 0x50136B, 0x0000, 0x0000, 0x0000, 0x501C78, 0x501C78, 0x0000, 0x0000, 0x0000, 0x0000, 0x501C78, 
0x501C74, 0x501C71, 0x501C71, 0x501C71, 0x501C77, 0x501C75, 0x0000, 0x0000, 0x501C78, 0x501C78, 0x0000, 0x0000, 0x0000, 0x0000, 0x501C78, 0x501C78, 
0x0000, 0x501C78, 0x501C78, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000, 0x501C78, 0x501C78, 0x0000, 0x0000, 0x0000, 0x0000, 0x501C78, 
0x501C78, 0x0000, 0x0000, 0x0000, 0x501C78, 0x501C78, 0x0000, 0x0000, 0x0000, 0x0000, 0x501C78, 0x501C78, 0x0000, 0x0000, 0x0000, 0x501C6D, 
0x501C75, 0x0000, 0x0000, 0x501C6D, 0x501C75, 0x0000, 0x0000, 0x0000, 0x0000, 0x501C74, 0x501C6A, 0x0000, 0x501C6D, 0x501C75, 0x0000, 0x0000, 
0x0000, 0x0000, 0x0000, 0x0000, 0x501C6D, 0x501C75, 0x0000, 0x0000, 0x0000, 0x0000, 0x501C74, 0x501C6A, 0x0000, 0x0000, 0x0000, 0x501C6D, 
0x501C6A, 0x0000, 0x0000, 0x0000, 0x0000, 0x501C6D, 0x501C6A, 0x0000, 0x0000, 0x0000, 0x0000, 0x501C6D, 0x501C71, 0x0000, 0x0000, 0x501C6D, 
0x501C71, 0x501C71, 0x501C71, 0x501C71, 0x501C6A, 0x0000, 0x0000, 0x0000, 0x501C6D, 0x501C71, 0x501C71, 0x501C71, 0x501C71, 0x501C71, 0x0000, 0x0000, 
0x501C6D, 0x501C71, 0x501C71, 0x501C71, 0x501C71, 0x501C6A, 0x0000	};

void draw_title(void);

void one_oponent(Truco *truco);
void two_oponents(Truco *truco);
void three_oponents(Truco *truco);
void options(Truco *truco);
void quit(Truco *truco);
void draw_rand_cards(Truco *truco, int *x_info, int *y_info);

void run_main_menu(Truco *truco) {
    Menu *menu;
    int r_card_x[RAND_CARD_COUNT], r_card_y[RAND_CARD_COUNT], i, w, h;

    /* Randimize card coords */
    getmaxyx(stdscr, h, w);
    for (i = 0; i < RAND_CARD_COUNT; i ++) {
        while ((r_card_x[i] = rand() % (w - 11)) < 50 &&
                (r_card_y[i] = rand() % (h - 6)) < 15);
    }
    deck_merge(truco->deck);

    menu = menu_new(truco, 26, 8, 22, 7);

    menu_add_item(menu, "    Un Oponente     ", one_oponent);
    menu_add_item(menu, "   Dos Oponentes    ", two_oponents);
    menu_add_item(menu, "   Tres Oponentes   ", three_oponents);
    menu_add_item(menu, "      Opciones      ", options);
    menu_add_item(menu, "       Salir        ", quit);

    while (!truco->exit_stage) {
        erase();
        wclear(menu->wnd);

        /* Random cards */
        draw_rand_cards(truco, r_card_x, r_card_y);

        /* Title */
        draw_title();

        /* Menu */ 
        menu_print(menu);

        refresh();
        wrefresh(menu->wnd);

        menu_key_event(menu, getch());
    }

    menu_clean(menu);
}

void one_oponent(Truco *truco) {
    truco->player_count = 2;
    start_game(truco);
    truco->stage = GAME_STAGE;
    truco->exit_stage = 1;
}

void two_oponents(Truco *truco) {
    truco->player_count = 4;
    start_game(truco);
    truco->stage = GAME_STAGE;
    truco->exit_stage = 1;
}

void three_oponents(Truco *truco) {
    truco->player_count = 6;
    start_game(truco);
    truco->stage = GAME_STAGE;
    truco->exit_stage = 1;
}

void options(Truco *truco) {
    truco->stage = OPTIONS_STAGE;
    truco->exit_stage = 1;
}

void quit(Truco *truco) {
    truco->exit_stage = 1;
    truco->quit = 1;
}

void draw_title(void) {
    int w = 43, h = 5, x, y, i = 0;

    for (y = 0; y < h; y ++)
		for (x = 0; x < w; x ++) {
			if (title_data[i]) mvaddch(y + 2, x + 5, title_data[i]);
			i ++;
		}

    attron(COLOR_PAIR(PAIR_TITLE));
    mvprintw(8, 6, "%s", "A R G E N T I N O");
    attroff(COLOR_PAIR(PAIR_TITLE));
}

void draw_rand_cards(Truco *truco, int *x_info, int *y_info) {
    int i;
    for (i = 0; i < RAND_CARD_COUNT; i ++) {
        if (i % 2) card_draw(stdscr, truco->deck[i], x_info[i], y_info[i]);
        else card_draw_small(stdscr, truco->deck[i], x_info[i], y_info[i]);
    }
}
